export const driverDetailsOptions = {
  states: [
    { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
    { value: 'Arunachal Pradesh', label: 'Arunachal Pradesh' },
    { value: 'Assam', label: 'Assam' },
    { value: 'Bihar', label: 'Bihar' },
    { value: 'Chhattisgarh', label: 'Chhattisgarh' },
    { value: 'Goa', label: 'Goa' },
    { value: 'Gujarat', label: 'Gujarat' },
    { value: 'Haryana', label: 'Haryana' },
    { value: 'Himachal Pradesh', label: 'Himachal Pradesh' },
    { value: 'Jharkhand', label: 'Jharkhand' },
    { value: 'Karnataka', label: 'Karnataka' },
    { value: 'Kerala', label: 'Kerala' },
    { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
    { value: 'Maharashtra', label: 'Maharashtra' },
    { value: 'Manipur', label: 'Manipur' },
    { value: 'Meghalaya', label: 'Meghalaya' },
    { value: 'Mizoram', label: 'Mizoram' },
    { value: 'Nagaland', label: 'Nagaland' },
    { value: 'Odisha', label: 'Odisha' },
    { value: 'Punjab', label: 'Punjab' },
    { value: 'Rajasthan', label: 'Rajasthan' },
    { value: 'Sikkim', label: 'Sikkim' },
    { value: 'Tamil Nadu', label: 'Tamil Nadu' },
    { value: 'Telangana', label: 'Telangana' },
    { value: 'Tripura', label: 'Tripura' },
    { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
    { value: 'Uttarakhand', label: 'Uttarakhand' },
    { value: 'West Bengal', label: 'West Bengal' },
    { value: 'Andaman and Nicobar Islands', label: 'Andaman and Nicobar Islands' },
    { value: 'Chandigarh', label: 'Chandigarh' },
    { value: 'Dadra and Nagar Haveli and Daman and Diu', label: 'Dadra and Nagar Haveli and Daman and Diu' },
    { value: 'Lakshadweep', label: 'Lakshadweep' },
    { value: 'Delhi', label: 'Delhi' },
    { value: 'Puducherry', label: 'Puducherry' },
  ],
  cities: [
    { value: 'Mumbai', label: 'Mumbai' },
    { value: 'Delhi', label: 'Delhi' },
    { value: 'Bengaluru', label: 'Bengaluru' },
    { value: 'Kolkata', label: 'Kolkata' },
    { value: 'Chennai', label: 'Chennai' },
    { value: 'Hyderabad', label: 'Hyderabad' },
    { value: 'Ahmedabad', label: 'Ahmedabad' },
    { value: 'Pune', label: 'Pune' },
    { value: 'Jaipur', label: 'Jaipur' },
    { value: 'Lucknow', label: 'Lucknow' },
    { value: 'Kanpur', label: 'Kanpur' },
    { value: 'Nagpur', label: 'Nagpur' },
    { value: 'Indore', label: 'Indore' },
    { value: 'Chandigarh', label: 'Chandigarh' },
    { value: 'Coimbatore', label: 'Coimbatore' },
  ],
  experience: [
    { value: '0', label: '0' },
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
    { value: '5', label: '5' },
  ],
  localities: [
    { value: 'Andheri', label: 'Andheri' },
    { value: 'Bandra', label: 'Bandra' },
    { value: 'Dadar', label: 'Dadar' },
    // Localities of Delhi
    { value: 'Connaught Place', label: 'Connaught Place' },
    { value: 'Karol Bagh', label: 'Karol Bagh' },
    { value: 'Dwarka', label: 'Dwarka' },
    // Localities of Bengaluru
    { value: 'Indiranagar', label: 'Indiranagar' },
    { value: 'Koramangala', label: 'Koramangala' },
    { value: 'Whitefield', label: 'Whitefield' },
    // Localities of Kolkata
    { value: 'Park Street', label: 'Park Street' },
    { value: 'Salt Lake', label: 'Salt Lake' },
    { value: 'Howrah', label: 'Howrah' },
    // Localities of Chennai
    { value: 'T. Nagar', label: 'T. Nagar' },
    { value: 'Anna Nagar', label: 'Anna Nagar' },
    { value: 'Velachery', label: 'Velachery' },
    // Localities of Hyderabad
    { value: 'Banjara Hills', label: 'Banjara Hills' },
    { value: 'Gachibowli', label: 'Gachibowli' },
    { value: 'Hitech City', label: 'Hitech City' },
  ],
}
